<?php

// https://www.advancedcustomfields.com/resources/register-fields-via-php/

return array (
    'key' => 'group_'.$blockName,
    'name' => $blockName,
    'label' => str_replace('-', ' ', ucfirst($blockName)),
    'display' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'field_'.$blockName.'_hide',
            'label' => 'Hide this block',
            'name' => 'hide',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '48',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),

        array(
            'key' => 'field_'.$blockName.'_section_header',
            'label' => 'Section header',
            'name' => 'section_header',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 0,
            'delay' => 0,
        ),


        array(
            'key' => 'field_5bd83267a1eee',
            'label' => 'Items',
            'name' => 'items',
            'type' => 'repeater',
            'instructions' => 'Promo box items to be displayed in this block.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'sub_fields' => array(
                array(
                    'key' => 'field_5bd8327da1eef',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_5bd83288a1ef0',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5bd83295a1ef1',
                    'label' => 'Secondary title',
                    'name' => 'secondary_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5bd832a1a1ef2',
                    'label' => 'Page link',
                    'name' => 'page_link',
                    'type' => 'page_link',
                    'instructions' => 'Choose which page this item should link to. For full utility, this page should have the Respa space block added to it.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'page',
                    ),
                    'taxonomy' => array(
                    ),
                    'allow_null' => 0,
                    'allow_archives' => 1,
                    'multiple' => 0,
                ),
                array(
                    'key' => 'field_5bd832c7a1ef3',
                    'label' => 'Purpose',
                    'name' => 'purpose',
                    'type' => 'select',
                    'instructions' => 'Selecting a purpose here pre-selects that option from the list in the Respa space reservation block.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'photo-and-audio' => 'Kuvaa tai ääntä',
                        'manufacturing' => 'Valmistaa esineitä, askarrella tai korjata',
                        'meetings-and-working' => 'Pitää kokouksen tai työskennellä',
                        'sports' => 'Liikkua tai pelata',
                    ),
                    'default_value' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_'.$blockName.'_color',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'select',
                    'instructions' => 'Select the colour scheme for this block',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'yellow' => 'Yellow',
                        'pink' => 'Pink',
                        'green' => 'Green',
                        'blue' => 'Blue',
                        'white' => 'White',
                    ),
                    'default_value' => array(
                        0 => 'yellow',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
            ),
        ),


    ),
    'min' => '',
    'max' => '',
);
