<?php

// https://www.advancedcustomfields.com/resources/register-fields-via-php/

return array (
    'key' => 'group_'.$blockName,
    'name' => $blockName,
    'label' => str_replace('-', ' ', ucfirst($blockName)),
    'display' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'field_'.$blockName.'_hide',
            'label' => 'Hide this block',
            'name' => 'hide',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '48',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_'.$blockName.'_info_columns',
            'label' => 'Info columns',
            'name' => 'info_columns',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 1,
            'max' => 4,
            'layout' => 'table',
            'button_label' => 'Add info column',
            'sub_fields' => array(
                array(
                    'key' => 'field_'.$blockName.'_icon',
                    'label' => 'Icon',
                    'name' => 'icon',
                    'type' => 'select',
                    'instructions' => 'Select the icon to display on this column',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'esteeton' => 'esteeton',
                        'kahvikuppi' => 'kahvikuppi',
                        'kova-aani' => 'kova-aani',
                        'lasi' => 'lasi',
                        'maapallo' => 'maapallo',
                        'paikkamerkki' => 'paikkamerkki',
                        'puu1' => 'puu1',
                        'sulje' => 'sulje',
                        'henkari' => 'henkari',
                        'kaksi-sydanta' => 'kaksi-sydanta',
                        'kyna' => 'kyna',
                        'lastenvaunut' => 'lastenvaunut',
                        'mies-ja-nainen' => 'mies-ja-nainen',
                        'pelikonsoli' => 'pelikonsoli',
                        'puu2' => 'puu2',
                        'surulliset-kasvot' => 'surulliset-kasvot',
                        'henkilo' => 'henkilo',
                        'kala' => 'kala',
                        'lahjapaketti' => 'lahjapaketti',
                        'lentokone' => 'lentokone',
                        'mies' => 'mies',
                        'polkupyora' => 'polkupyora',
                        'roskakori' => 'roskakori',
                        'suu' => 'suu',
                        'ilmapallo' => 'ilmapallo',
                        'kannu' => 'kannu',
                        'lainausmerkki' => 'lainausmerkki',
                        'linnut' => 'linnut',
                        'nainen' => 'nainen',
                        'porkkana' => 'porkkana',
                        'saapas' => 'saapas',
                        'suurennuslasi' => 'suurennuslasi',
                        'iloiset-kasvot' => 'iloiset-kasvot',
                        'kello' => 'kello',
                        'laiva' => 'laiva',
                        'lisaa' => 'lisaa',
                        'oikein' => 'oikein',
                        'puhekupla' => 'puhekupla',
                        'sateenvarjo' => 'sateenvarjo',
                        'sydan' => 'sydan',
                        'info' => 'info',
                        'kirja' => 'kirja',
                        'lamppu' => 'lamppu',
                        'lumihiutale' => 'lumihiutale',
                        'omena' => 'omena',
                        'pullonavaaja' => 'pullonavaaja',
                        'silmalasit' => 'silmalasit',
                        'talo' => 'talo',
                    ),
                    'default_value' => array(
                        0 => 'esteeton',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_'.$blockName.'_color',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'select',
                    'instructions' => 'Select the icon color',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'black' => 'Black (default)',
                        'white' => 'White',
                        'yellow' => 'Yellow',
                        'pink' => 'Pink',
                        'green' => 'Green',
                        'blue' => 'Blue',
                    ),
                    'default_value' => array(
                        0 => 'black',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_'.$blockName.'_text',
                    'label' => 'Text',
                    'name' => 'text',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                ),
                array(
                    'key' => 'field_'.$blockName.'_number',
                    'label' => 'Number',
                    'name' => 'number',
                    'type' => 'text',
                    'instructions' => 'The numeric value to be presented in this column',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
        ),

    ),
    'min' => '',
    'max' => '',
);
